import { AdminAssigned } from '~/modules/adminAssigned/types';
import { CandidatesState } from '~/modules/adminCandidates/types';
import { ContactsState } from '~/modules/adminContacts/types';
import { AdminDashboardState } from '~/modules/adminDashboard/types';
import { AdminProfileState } from '~/modules/adminEditProfile/types';
import { EmployersState } from '~/modules/adminEmployers/types';
import { AdminLiveJobsState } from '~/modules/adminLiveJobs/types';
import { AdminMessagingState } from '~/modules/adminMessaging/types';
import { AdminMatchedJobsPipelineState } from '~/modules/adminPipeline/types';
import { AdminTimesheetState } from '~/modules/adminTimesheet/types';
import { AdminUserState } from '~/modules/adminUser/types';
import { AdminWhiteboardState } from '~/modules/adminWhiteboard/types';
import { CandidateFindJobsState } from '~/modules/candidateFindJobs/types';
import { CandidateProposalsState } from '~/modules/candidateProposals/types';
import { CandidateRegistrationState } from '~/modules/candidateRegistration/types';
import { CandidateTimesheetState } from '~/modules/candidateTimesheet/types';
import { CandidateUserState } from '~/modules/candidateUser/types';
import { CommonState } from '~/modules/common/types';
import { CompanyState } from '~/modules/companies/types';
import { CompanyCandidatesState } from '~/modules/companyCandidates/types';
import { CompanyProfileState } from '~/modules/companyEditProfile/types';
import { CompanyInterestedInState } from '~/modules/companyInterested/types';
import { CompanyInterviewsState } from '~/modules/companyInterviews/types';
import { CompanyJobsState } from '~/modules/companyJobs/types';
import { MyJobsState } from '~/modules/companyMyJobs/types';
import { CompanyRegistrationState } from '~/modules/companyRegistration/types';
import { CompanyTimesheetState } from '~/modules/companyTimesheet/types';
import { CompanyUserState } from '~/modules/companyUser/types';
import { CreateCandidateState } from '~/modules/createCandidate/types';
import { CreateEmployerState } from '~/modules/createEmployer/types';
import { CreateJobState } from '~/modules/createJob/types';
import { HiringManagerUserState } from '~/modules/hiringManager/types';
import { ManageAdminsState } from '~/modules/manageAdmins/types';
import { NotificationState } from '~/modules/notifications/types';
import { PopupsState } from '~/modules/popups/types';
import { RegistrationState } from '~/modules/registration/types';
import { ShortListState } from '~/modules/shortlist/types';
import { SuperAdminUserState } from '~/modules/superAdminUser/types';
import { UserState } from '~/modules/user/types';

export interface RootState {
  common: CommonState;
  registration: RegistrationState;
  candidateRegistration: CandidateRegistrationState;
  companyRegistration: CompanyRegistrationState;
  user: UserState;
  adminUser: AdminUserState;
  candidateUser: CandidateUserState;
  companyUser: CompanyUserState;
  adminLiveJobs: AdminLiveJobsState;
  adminCandidates: CandidatesState;
  adminEmployers: EmployersState;
  createJob: CreateJobState;
  createCandidate: CreateCandidateState;
  adminContacts: ContactsState;
  createEmployer: CreateEmployerState;
  adminMatchedJobsPipeline: AdminMatchedJobsPipelineState;
  candidateProposals: CandidateProposalsState;
  companyInterviews: CompanyInterviewsState;
  adminProfile: AdminProfileState;
  candidateFindJobs: CandidateFindJobsState;
  companyProfile: CompanyProfileState;
  companyCandidates: CompanyCandidatesState;
  companyJobs: CompanyJobsState;
  candidateTimesheet: CandidateTimesheetState;
  shortList: ShortListState;
  companyTimesheet: CompanyTimesheetState;
  adminDashboard: AdminDashboardState;
  companyMyJobs: MyJobsState;
  companies: CompanyState;
  notifications: NotificationState;
  manageAdmins: ManageAdminsState;
  adminMessaging: AdminMessagingState;
  hiringManagerUser: HiringManagerUserState;
  superAdminUser: SuperAdminUserState;
  adminAssigned: AdminAssigned;
  companyInterestedIn: CompanyInterestedInState;
  successPopup: PopupsState;
  adminTimesheet: AdminTimesheetState;
  adminWhiteboard: AdminWhiteboardState;
}
